### PR TITLE
a first go at the OBO...

### PR DESCRIPTION
**Pull request by cbielow**
changes to be discussed:

I have made some changes to the OBO structure, in particular:
 - added `sample preparation metric` as child to QC metric
 - added `MS metric` as layer between `QC metric` and `MS1 metric` (same for MS2)
 - started changing some IDs:
    - the idea is that the IDs somewhat reflect the tree/graph structure, such that a knowledgable user ca n infer that `QC:4001????` must be a some sort of RT metric... not sure of this is a) allowed b) agreeable
 - the `ambient humidity` had a TODO (why n-tuple #64 ). I just came up with something completely different (corresponding lists), hoping that this would make sense. To be discussed I guess :)
 - some minor typos and low/uppercase fixes to make everything a bit more uniform
 - I removed (out of ignorance) the qc-cv-legacy-0.0.8.obo. Why was that present? It seems to me it should not carry over... Can someone enlighten me :)

I'll open up another issue with related questions...
PTXQC metrics are next on my list. Coming soon...

note: my `Protege` editor reorders some lines automagically. I hope thats ok...

### CODE REVIEW

**Comment by cbielow** [comment]
image

**Comment by bittremieux** [comment]
There is a simple resolution for issue #64. @julianu should just incorporate that in the next version of the CV.

Your list-of-lists solution as it is described at the moment doesn't seem ideal because ambient humidity will typically come from an external sensor, so there's no direct link to RT. At least this would be the case for my iMonDB software, where I report ambient humidity. I also only retain a single (average) ambient humidity value for each run to condense the amount of data.

**Comment by mwalzer** [comment]
>>> removed (out of ignorance) the qc-cv-legacy-0.0.8.obo
the file or the include statement?

**Comment by cbielow** [comment]
t

> 
> 
> > removed (out of ignorance) the qc-cv-legacy-0.0.8.obo
> 
> the file or the include statement?

the include
https://github.com/HUPO-PSI/mzQC/pull/71/files#diff-77d9fee4d2a21e086c38ee88e00ad9f4L7

**Comment by mwalzer** [comment]
> a bit more uniform

I think we should define our style guide. #74

**Comment by mwalzer** [comment]
> I just came up with something completely different (corresponding lists)
We were aware that there will be ambiguities, and I think this is a good place to discuss and document (I won't use a word as strong as guidelines here) our design intentions. It was mentioned in a previous call that if we have all different designs from different metric producers we take a cut in the added value of a common format. Having a well-discussed (specification document supplement?) rationale for our design decisions might help bring people to a common base.

**Comment by mwalzer** [comment]
Further discussion point may be the separation between `chromatogram metric` and `retention time metric`

**Comment by julianu** [comment]
> > removed (out of ignorance) the qc-cv-legacy-0.0.8.obo
> 
> only the import statement or the file also? I agree the legacy import shouldn't be imported, however the file itself should be available.

To keep a backlink to this file, the file was linked. We should keep the link there, if we need some kind of "backwards compatibility" with the old version. But if especially @mwalzer is happy to delete it, I would be perfectly fine to delete it as well.

> started changing some IDs: 
This might not be such a good idea. Usually, in the other PSI OBOs, the IDs are simply increasing numbers. To somewhat distinguish our CV from the legacy qcML-CVs, I put the 4 in the beginning. But I don't know whether we should use the IDs to categorize items. Maybe @Ozzard has any suggestions here?

**Comment by mwalzer** [comment]
>  @mwalzer is happy to delete it,

Remove the mention of the legacy obo in our master obo? Fine by me. The legacy obo file itself we can ban to the `legacy` folder. We could see to avoid uid clashes, but that's sugar on top, don't bother if this complicates things

**Comment by julianu** [comment]
> Remove the mention of the legacy obo in our master obo? Fine by me. The legacy obo file itself we can ban to the `legacy` folder. We could see to avoid uid clashes, but that's sugar on top, don't bother if this complicates things

Ok, then we can keep this out of the new overhauled OBO file.

Only the issue with increasing IDs needs to be discussed (in the upcoming call?). All other changes are ok for me.

**Comment by Ozzard** [comment]
> > started changing some IDs:

> This might not be such a good idea. Usually, in the other PSI OBOs, the IDs are simply increasing numbers. To somewhat distinguish our CV from the legacy qcML-CVs, I put the 4 in the beginning. But I don't know whether we should use the IDs to categorize items. Maybe @Ozzard has any suggestions here?

I'm a great fan of allocating an ID for a concept exactly once and never, ever changing it; and treating an ID as having no meaning.  It's an opaque bundle of bits.

There are several reasons for this:
* Over time, the ID becomes embedded in bits of software, configuration files, tutorials, databases, and cross-links from other information.  Change the ID and all dependents are out of date.  Don't ever assume that just because you've trawled through all the information you can, you're in the clear.  See, for example, https://github.com/PaulBrack/Yamato/blob/master/SwaMe/FileMaker.cs .
* As you release new versions of controlled vocabularies, you tend to add new terms and retire old ones.  Even if your original terms fitted into whatever gaps you left in your numbering scheme, there's no guarantee you won't breach them with subsequent additions.  Almost the canonical example of this is version 2 of the Read Clinical Classification ("the Read Codes"), which used 4- and 5-character hierarchical codes with upper case, lower case and digits (so 62 options) available at each level of the hierarchy.  Read then promptly tried to code things like "job" (starting with "Prime Minister" and working down) and "interpreter required for <language>", and blew the namespace.  Read version 3, and the mapping to SNOMED, simply uses random term codes, with a side data structure to represent hierarchy, and is far better for that change.

Happy to discuss, but my working approach would be to attach no meaning to IDs and to distribute a separate file of groupings/hierarchy and another of equivalences if required.  Easier extension, easier versioning.

**Comment by Ozzard** [comment]
> Only the issue with increasing IDs needs to be discussed (in the upcoming call?).

I'm not part of the WG, but would appreciate having some input into this decision if you don't have a librarian / taxonomist* / ontologist in the WG.

\* (Someone who maintains hierarchies of terms, not someone who stuffs animals - though the slight smell of preservation is common to the two)

**Comment by julianu** [comment]
Thanks for the input, @Ozzard 

We will drop the categorisation-attempt of the IDs and just use them in increasing order.
I will change this in the next few days and accept the PR.

**Comment by cbielow** [comment]
> 
> 
> > > started changing some IDs:
> 
> > This might not be such a good idea. Usually, in the other PSI OBOs, the IDs are simply increasing numbers. To somewhat distinguish our CV from the legacy qcML-CVs, I put the 4 in the beginning. But I don't know whether we should use the IDs to categorize items. Maybe @Ozzard has any suggestions here?
> 
> I'm a great fan of allocating an ID for a concept exactly once and never, ever changing it; and treating an ID as having no meaning. It's an opaque bundle of bits.
> 
> There are several reasons for this:
> 
>     * Over time, the ID becomes embedded in bits of software, configuration files, tutorials, databases, and cross-links from other information.  Change the ID and all dependents are out of date.  Don't ever assume that just because you've trawled through all the information you can, you're in the clear.  See, for example, https://github.com/PaulBrack/Yamato/blob/master/SwaMe/FileMaker.cs .

Point well taken, but the mzQC standard is not released yet, thus no one should be using the current IDs (or trust they are stable). With the first release, we should not ever touch them, of course.

> 
>     * As you release new versions of controlled vocabularies, you tend to add new terms and retire old ones.  Even if your original terms fitted into whatever gaps you left in your numbering scheme, there's no guarantee you won't breach them with subsequent additions.  Almost the canonical example of this is version 2 of the Read Clinical Classification ("the Read Codes"), which used 4- and 5-character hierarchical codes with upper case, lower case and digits (so 62 options) available at each level of the hierarchy.  Read then promptly tried to code things like "job" (starting with "Prime Minister" and working down) and "interpreter required for <language>", and blew the namespace.  Read version 3, and the mapping to SNOMED, simply uses random term codes, with a side data structure to represent hierarchy, and is far better for that change.
> 

Very interesting! Will keep that in mind.

> 
> Happy to discuss, but my working approach would be to attach no meaning to IDs and to distribute a separate file of groupings/hierarchy and another of equivalences if required. Easier extension, easier versioning.

Fair point. Thanks for the input. :)

**Pull request merged**
