### PR TITLE
schema changes to v0.10

### PR DESCRIPTION
**Pull request by mwalzer**
Rebased

### CODE REVIEW

**Comment by bittremieux** [comment]
Can you make sure to rebase before merging when the schema changes for version 0.10 are complete?

**Comment by mwalzer** [comment]
Yes, the schemas' metadata section needs some improvements. I recall we briefly discussed parts of the metadata section, so once I'll review the minutes, I will update the branch and try to resolve conflicts. the changes to the CV were metric additions and term definition refinements, so I'd rather not loose them

**Comment by julianu** [comment]
Ok. For the CV: I will have a look at the changes in this PR and add them to a new slightly cleaned version (0.0.11?), which will cover the discussed topics.

**Comment by mwalzer** [comment]
TY!

On 25/04/18 08:30, Julian Uszkoreit wrote:
> Ok. For the CV: I will have a look at the changes in this PR and add them to a new slightly cleaned version (0.0.11?), which will cover the discussed topics.
>

-- 
Mathias Walzer
European Bioinformatics Institute (EMBL-EBI)
Wellcome Trust Genome Campus, Hinxton, Cambridge, UK
Office: +44 (0)1223 494 2610
E-mail: walzer@ebi.ac.uk

**Comment by mwalzer** [comment]
deprecated w/ move to json

**Pull request closed without merging**
