### PR TITLE
Cross-linked Markup version of obo.

### PR DESCRIPTION
**Pull request by nilshoffmann**
If needed, I can provide the script to build this automatically as part of CI.

### CODE REVIEW

**Comment by mwalzer** [comment]
I love it, perfect for bridging the time until we are ready for OLS integration. I need to go over the CI issues soon, anyway, so an automated update of the obo's representation would be bliss.

**Comment by nilshoffmann** [comment]
Scripts for that are here: https://github.com/nilshoffmann/obo-adoc
Just need groovy (e.g. via sdkman: https://sdkman.io/install), edit the ontology-urls.ini (or recreate it containing just the link to https://raw.githubusercontent.com/HUPO-PSI/mzQC/master/cv/qc-cv.obo). Then run ./dtr.sh and copy the final target/qc-cv.adoc and target/qc-cv.adoc to your desired location.

**Comment by nilshoffmann** [comment]
See #119 for an update on the current location of the qc-cv html.

**Comment by bittremieux** [comment]
@nilshoffmann Could you try to update this PR to include:
- A GitHub Actions workflow so that the HTML page is automatically updated upon each commit/merge.
- Rather than including the raw HTML in the `cv` folder, make it so that the updated pages are hosted on our GitHub Pages website.

**Comment by nilshoffmann** [comment]
The latest PR includes the required dependencies in the .build-tools folder and builds the obo html in the temporary build/target folder. The workflow also adds a Jekyll step which probably needs to be adjusted for the current jekyll page, which exists on the gh-pages branch.

**Comment by mwalzer** [comment]
This is awesome @nilshoffmann . If I read that last step of the workflow right, it will deposit a `qc-cv.html` into the root of the gh-pages branch? Then, integration is simple with just adding that file to the _config.yml header_pages listing to make it a 1st class citizen. I don't have much experience with jekyll generally (this is partly why it took me so long to get the validator online), maybe you could give it a stab after this PR is merged?

**Comment by nilshoffmann** [comment]
@mwalzer @bittremieux If we integrate with PSI-MS, do we still need the browseable html version?

**Comment by bittremieux** [comment]
I agree, that's something to discuss. If the CV is on OBOFoundry, through integration with the MS CV, it's easily browsable on there. So that might solve that issue.

**Comment by mwalzer** [comment]
Agreed, I don't think we need that. Yet, I think it's a nice feature, maybe at some point for the merged MS .obo?

**Comment by bittremieux** [comment]
No longer necessary now we are [ready to merge into PSI-MS-CV](https://github.com/HUPO-PSI/psi-ms-CV/pull/99). Thanks for the effort @nilshoffmann!

**Pull request closed without merging**
